cashladder.ipynb, cashladder.py
Add cashladder example
Add cashladder script
=> Add cashladder example

examples/use-cases/Instruments.ipynb
changed the properties response to use as_at_date instead of additional
properties
=>  Removed the list instruments method until pagination is completed and 

examples/use-cases/Instruments.ipynb, examples/use-cases/printer.py
=> DEV-4522 Update for API changes

README.md
added a link to the "Getting started with the LUSID API and SDKs" help page, which describes how to compose the secrets.json file
=> Edit to README 

examples/use-cases/Load Transactions from an External System.ipynb
As discussed, I have made the following amendments:
(1) Removed redundant printing of ext_sys_df DataFrame
(2) Removed the two blank cells at the end
=> remove redundant code

examples/use-cases/Households.ipynb, examples/use-cases/Maintain a fund in multiple currencies and share classes.ipynb, examples/use-cases/Supporting a multi-asset class book of business.ipynb
Reverts finbourne/sample-notebooks#124
=> Revert "DEV-5950 Updated the scope of data types for property definitions fro…"

examples/modules/aggregation.ipynb, examples/modules/bitemporal-backtrade.ipynb, examples/modules/cashladder.ipynb, examples/use-cases/Backtesting with LUSID derived portfolios.ipynb, examples/use-cases/Business Agility - migration between investment systems.ipynb, examples/use-cases/Generate P&L with different accounting methods (FIFO and LIFO).ipynb, examples/use-cases/Generating Corporate actions natively in LUSID.ipynb, examples/use-cases/Get a consolidated view of your data from multiple systems.ipynb, examples/use-cases/Households.ipynb, examples/use-cases/Load Transactions from an External System.ipynb, examples/use-cases/Loading data with the Lusid-Python-Tools (LPT) package.ipynb, examples/use-cases/Maintain a fund in multiple currencies and share classes.ipynb, examples/use-cases/Maintaining an instrument master in LUSID.ipynb, examples/use-cases/Manage your investment strategies.ipynb, examples/use-cases/Managing cashflows - subscriptions and redemptions.ipynb, examples/use-cases/Perform a reconciliation.ipynb, examples/use-cases/Portfolio types and portfolio groups in LUSID.ipynb, examples/use-cases/Running a Global Fund.ipynb, examples/use-cases/Safely and efficiently test changes to your system.ipynb, examples/use-cases/Set up a sandbox trading environment-DEMO.ipynb, examples/use-cases/Set up a sandbox trading environment.ipynb, examples/use-cases/Supporting a multi-asset class book of business.ipynb, examples/use-cases/Track trading commissions in your portfolio.ipynb, examples/use-cases/Using cut-labels to manage your business across different time-zones.ipynb
Updated each notebook to attempt to load credentials from a secrets.json located in the examples folder.
Also added `from lusidjam import  RefreshingToken` for examples\modules\*.ipynb
```python
secrets_path = os.path.join(os.pardir, "secrets.json")
if os.path.exists(secrets_path):
api_factory = lusid.utilities.ApiClientFactory(api_secrets_filename=secrets_path)
else:
api_factory = lusid.utilities.ApiClientFactory(
token=RefreshingToken(),
app_name="LusidJupyterNotebook"
)
print ('LUSID Environment Initialised')
print ('LUSID SDK Version: ', api_factory.build(lusid.api.ApplicationMetadataApi).get_lusid_versions().build_version)
```
=> Feature/dev 6768.update api client authentication

.travis.yml
Adds FBN_APP_NAME to travis builds
=> SE-322 Add app name 

examples/features/core-lusid/TimeVariant Properties.ipynb, examples/features/core-lusid/data/equity_transactions_isin.csv
-Example notebook for time-variant properties 
-Show bi-temporality of time-variant properties (asAt/EffectiveAt)
=> SE-429: Adding example notebook for time-variant properties

examples/use-cases/post-trade-processing/Managing a transaction lifecycle using LUSID's properties.ipynb
changing scope from randomly generated to 'booking_sample'
=> SE-212 changing scope from randomly generated to 'transaction_lifecycle'

examples/features/core-lusid/Multi-Value Properties.ipynb
Added Example notebook for using multi-value properties. 
- Use a schedule to upsert a multi-value property to a portfolio
- Query on an effective date and see forward-looking values
=> SE-441/Added Multi-Value Properties example notebook

.github/workflows/main.yml
Amending the slack message on PR failure.
=> Feature/se 463.gha slack message on failure

.github/workflows/slack-on-pr.yml
=> SE-545: add slack alert on PR

.github/workflows/cron.yml, .github/workflows/main.yml
Making GitHub action names consist across projects
=> SE-462: update GHA action names

examples/use-cases/valuation/Bond Pricing And Accrued Interest Calculation.ipynb
- Fixed failed output on Bond And Accrued Interest Calculation in sample notebooks
- Added formatting for large values and set accuracy to 3 s.f.
=> SE-656: Fixed failed output on Bond And Accrued Interest notebook

examples/use-cases/valuation/Bond Pricing And Accrued Interest Calculation.ipynb
changing `get_aggregation_of_weighted_instruments` to  `get_valuation_of_weighted_instruments`
=> Feature/se 803.migrate notebooks valuation endpoint

examples/use-cases/valuation/Look-through valuation.ipynb, examples/use-cases/valuation/config/upload_config.json, examples/use-cases/valuation/data/equity_uk_us_data.csv, examples/use-cases/valuation/data/parent_fund_holdings.csv
Add client-facing look-through valuation notebook.
=> Add look-through valuation notebook

examples/features/core-lusid/Processing Corporate Actions as native LUSID transitions.ipynb
Pull request changing scope from randomly generated to "ca_transitions_demo"
=> SE-265 changing scope from randomly generated to 'ca_transitions_demo'

examples/use-cases/ibor/How do I create holdings in LUSID.ipynb
Fix to not create cash instruments
=> SE-1094 Fix to not create cash instruments

examples/use-cases/orders-management/Combining FO and MO.ipynb
Upsert property definition for the strategy property
=> PLAT-228: prop def for Allocation

examples/use-cases/risk-and-performance/Loading and calculating returns.ipynb
=> DEV-11053: Rename the W/M/Y metrics to W/M/Y -Rolling

examples/use-cases/ibor/IBOR User Journey.ipynb, examples/use-cases/ibor/helper_functions.py
- couple of stray uses of aggregation. Not used in any calculation but includes etc..
=> DEV-10688 : remove remaining aggregation uses to fix notebook tests

examples/use-cases/risk-and-performance/Returns on composite portfolios.ipynb
DEV-11243: Fix the composite relation definition to have the lifeTime: TimeVariant and add delete relationships events
=> DEV-11243: Fix the composite relation definition to have the lifeTime: TimeVariant and add delete relationships events

docgen/README.mustache, docgen/nbmeta.py, docgen/parser.py, examples/README.md
This PR updates the generation of the examples/README page to include links to individual notebooks rather than just their file names.
https://user-images.githubusercontent.com/13220/121328788-8b5f4800-c90c-11eb-8975-72d474d80145.mp4
=> Examples readme

.github/workflows/main.yml, examples/entitlements/Portfolio Entitlements.ipynb
Addition of EffectiveDateRelative forSpec policy example
Developed/Tested by running the sample jupyter notebooks on my lusid test domain.
=> IAM-297: forSpec example

examples/use-cases/risk-and-performance/Returns on composite portfolios.ipynb
DEV-11599: Try/catch delete the relationship, you can safely assume the relationship is not there anyway.
=> DEV-11599: Try/catch delete the relationship, you can safely assume the relationship is not there anyway.

examples/use-cases/valuation/Futures Valuation with Differing Cost Basis Treatments.ipynb
Added table of contents to notebook.
=> SE-1843: Futures PnL Cash Methodology Notebook - added table of contents

examples/use-cases/ibor/Maintaining an instrument master in LUSID.ipynb
=> SENG-56: comment out delete instruments

examples/use-cases/ibor/Perform a reconciliation.ipynb
=> Fixed two typos in content

examples/README.md
=> Fixed formatting issue on example-notebooks example README.md.

examples/use-cases/instruments/Equity Options - Pricing and risk using Black-Scholes.ipynb
=> SE-2287: Update - correct format of print msg

examples/use-cases/instruments/FX Forward.ipynb
- [+] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [+] Tests pass
- [+] Raised the PR against the `develop` branch
See comments under: https://finbourne.atlassian.net/browse/SE-2311
=> Update FX Forward.ipynb

examples/entitlements/Portfolio Entitlements.ipynb, examples/entitlements/Property value entitlements.ipynb
Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>
Some very bizarre behaviour, but this fixes the issue.
=> CTECH-1344: Fixes tests.

examples/use-cases/valuation/Valuations with Inferred FX Rates.ipynb
=> SE-2361: Updated queryable keys in aggragation API call

examples/use-cases/instruments/FX Forward.ipynb
https://finbourne.atlassian.net/browse/SE-2311
Further change to fix bug in notrebook
=> Fix Issue in FX Forward notebook

standalone/lusid.ipynb
Change the example used in the standalone from list scopes to instrument identifiers as the previous call can timeout
=> Update standalone example 

.github/workflows/build-and-test.yaml, .github/workflows/main.yml, docker-compose.yml, requirements.txt
Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>
Enables contributors to fork the repo and provide changes via the Forked Repo workflow. This removes the administrative overhead of having to add individuals as contributors to the organisation, and helps restrict those with approval capabilities.
Tests have been run locally, and match up with those that are run internally.  This PR will need to be merged before confirmation of the efficacy of the workflow actions changes can be confirmed.
=> CTECH-1723: Enables forked PR workflow.

.github/workflows/slack-on-pr.yml
Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>
Ensures that the forked PR's raise a slack notification without error.
=> CTECH-1723: Fixes the slack notification for forked PR's

.github/workflows/build-and-test.yaml, .github/workflows/slack-on-pr.yml
Signed-off-by: Paul Saunders <paul.saunders@finbourne.com>
The docker-compose file in this repo is located differently to the others in this org.  The build-and-test workflow needed to be modified to enable tests to run during a forked PR test run.
As a workflow only change, the test passing/failing should have no impact on the decision to merge.
=> CTECH-1723: Fixes the build specific to this repo.

.github/workflows/build-and-test.yaml
Changes the build-and-test workflow to add the correct env vars to accomodate the forked PR flow.
=> CTECH-1723: Fixes the build workflow

examples/use-cases/ibor/Generating Corporate actions natively in LUSID.ipynb
=> CTECH-1667 TCtypo

examples/use-cases/models-and-indices/Setting up a blended benchmark with floating weights.ipynb
**Changes:**
- Fix errors in Jupyter Notebooks (`Setting up blended benchmark with floating weights.ipynb`)
- Specify scope when fetching instruments from **LUSID**
- Using dictionary comprehension in place of a lambda function
- Add a try-exception block to delete Reference Portfolio and Securitised Instruments
=> SE-2495: Fix - errors in Setup rebalancer notebook

examples/modules/cashladder.py, examples/use-cases/audit-trail/Identifying Downstream Consumers affected by Backdated Corrections on a Locked Reporting Window.ipynb, examples/use-cases/valuation/Futures Valuation with Differing Cost Basis Treatments.ipynb
Details here: https://finbourne.atlassian.net/browse/SE-2703
=> Files updated to work with local secrets

examples/use-cases/ibor/Maintaining an instrument master in LUSID.ipynb
Update existing Notebook and add Instrument Scopes.
=> SE-2724: Add Instrument Scope

examples/use-cases/post-trade-processing/Transactions with Trade To Portfolio Rate.ipynb
Trade To Portfolio Rate Notebook
PR for Trade to Portfolio Rate notebook, previous pull request linked below:
https://github.com/finbourne/sample-notebooks/pull/481
=> SE-2092: First commit of notebook using new fork git method

examples/use-cases/data-quality-control/Custom Entities.ipynb
Update to accommodate change of behaviour from upsert to create only
=> PLAT-1737 fix change in behaviour when creating custom entities

.github/workflows/main.yml, docker-compose.yml
=> CTECH-2204: Add concurrent flag to build and PR steps.

examples/use-cases/ibor/Get a consolidated view of your data from multiple systems.ipynb
=> DEV-13204: Updating Portfolio Groups samples to support cut label

university/T01004-Portfolio-holding-reconciliation/T01004-Portfolio-holding-reconciliation.ipynb
=> CTECH-2307: Corrected typo in step 7.

requirements.txt
=> CTECH-2278 Added rise package to local docker container

examples/use-cases/ibor/Upserting a Large Payload.ipynb
=> SE-2888: Example Notebook How to Upsert Large Batches

examples/use-cases/risk-and-performance/Loading and calculating returns.ipynb
=> SE-2869 Added link to WebUI, plus slideshow tags

docker-compose.yml
=> CTECH-2300: Only run tests on changed files

examples/entitlements/Access Metadata entitlements.ipynb
Fix failing test. Change to code is on line 625 of notebook diff.
=> Remove code comment

examples/use-cases/ibor/How do I create holdings in LUSID.ipynb
Add missing property definitions to notebook and tear down to delete example data
=> add missing property definitions to notebook

examples/use-cases/data-quality-control/Custom Entities.ipynb
- [x ] Changes follow the [style guide](https://github.com/finbourne/sample-notebooks/blob/master/docs/FINBOURNE%20notebook%20style%20guide.ipynb)
- [ x] Tests pass
- [ x] Raised the PR against the `develop` branch
Ran notebook to produce cell output.
=> SE-2904: Ran Custom Entities notebook to capture output

docker-compose.yml
=> CTECH-2666: fix PR tests

.github/workflows/cron.yml, .github/workflows/main.yml
Add other SDK urls to daily build.
=> CTECH-2763: Add SDK urls to daily builds.

.github/workflows/cron.yml, .github/workflows/main.yml
Consolidate env variables for develop and master branch test runs. Fix variable interpolation by adding spaces.
=> CTECH-2763: fix daily build and consolidate variables

university/T11001-WhatAreQuotes/T11001-WhatAreQuotes.ipynb
=> CTECH-2605 Add notebook for T11001 What Are Quotes course

university/T09004-EventsAndNotifications-SendingWebhooks/T09004-EventsAndNotifications-SendingWebhooks.ipynb
=> CTECH-2656 Add T09004 Notebook

examples/use-cases/audit-trail/Requesting log details using the Insights API.ipynb
Increasing request bodies backoff max time to 60 seconds
=> Increasing request bodies backoff max time to 60 seconds

university/T11002-WorkingWithQuotes/T11002-WorkingWithQuotes.ipynb
=> CTECH-2605 Added notebook for T11002 Working with Quotes

university/T09002-EventsAndNotifications-SubscribingToEvents/T09002-EventsAndNotifications-SubscribingToEvents.ipynb
=> CTECH-2595 Added notebook for T09002

examples/use-cases/audit-trail/Requesting log details using the Insights API.ipynb
Notebook still failing integration tests with the requests backoff loop waiting 60s, so increasing to 120s.
=> Increasing request bodies backoff loop max time to 120s

university/T10001-WhatIsDrive/T10001-WhatIsDrive.ipynb
=> CTECH-2601 Added notebook for T10001 What is Drive?

examples/use-cases/instruments/Interest Rate Swap.ipynb
=> SE-3146: Add clean up section to InterestRateSwap

examples/use-cases/valuation/Look-through valuation.ipynb
=> Update Look-through valuation.ipynb

examples/use-cases/valuation/Look-through valuation (multi-level).ipynb
=> remove inlined index from sample notebooks

examples/use-cases/instruments/Term Deposit.ipynb
Update notebook with Cashflow broken down into Notional and Interest. 
Should fix failing tests in LUSID pipeline.
=> SE-3151: cashflow with notional and interest

Index.ipynb, examples/use-cases/instruments/Term Deposit.ipynb
Reverts finbourne/sample-notebooks#701
=> Revert "SE 3151.revert"

Index.ipynb, examples/use-cases/instruments/Term Deposit.ipynb
Reinstates and fixes Term Deposit notebook. Changes since it was reverted: 
* Changed scope from `ibor` to `TermDepositNotebook` to reduce concurrency issues in pipeline. 
* Add scope to instruments
* Respond to @rizwansaeed comments from [previous review](https://app.reviewnb.com/finbourne/sample-notebooks/pull/699/)
=> Feature/SE-3151: Term Deposit with Instrument Scope 

Index.ipynb, examples/use-cases/audit-trail/Identifying Downstream Consumers affected by Backdated Corrections on a Locked Reporting Window.ipynb
=> SECOPS-435: Fix sample notebook query

.github/workflows/cron.yml
use -c flag to run notebooks in parallel
=> CTECH-3216: run daily build in parallel

examples/use-cases/instruments/FX Option - 2 Trade comparison worksheet.ipynb, examples/use-cases/instruments/FX Option Vanilla Risk Ladders.ipynb
Removing deprecated valuation / risk / spot delta key.
=> ANA-1946: Removing deprecated valuation / risk / spot delta key.

examples/use-cases/valuation/Simple Valuation.ipynb
=> Update simple valuation to create recipe

examples/use-cases/ibor/Creating Portfolios With Different Tax Lot Management Methods.ipynb, examples/use-cases/ibor/data/taxlot_accounting_backdated_transactions.csv
=> SA-118 Add an example of backdating a sale and a correction

university/T12003-Properties-PopulatingPerpetualPropertyValues/T12003-Properties-PopulatingPerpetualPropertyValues.ipynb
=> CTECH-2623 Add notebook for T12003 Populating Perpetual Property Values

university/R03001-OperationalControls-AuthoringOperationalControls/R03001-OperationalControls-AuthoringOperationalControls.ipynb
=> CTECH-2829 Add notebook for R03001

university/R03002-OperationalControls-SavingResultsAndTakingActions/R03002-OperationalControls-SavingResultsAndTakingAction.ipynb
=> CTECH-2830 Added T03002 Notebook

university/T12001-Properties-LUSIDsExtensibleDataModel/T12001-Properties-LUSIDsExtensibleDataModel.ipynb
=> T12001 Add notebook explaining LUSID's extensible data model

university/T12005-Properties-ViewingAPropertysHistory/T12005-Properties-ViewingAPropertysHistory.ipynb
=> T12005 Add notebook for viewing a property's history

Dockerfile
=> CTECH-3308: Update base image to latest python version

examples/use-cases/instruments/Mortgage Backed Securities.ipynb
=> ANA-2987: Client demo notebook of Mortgage Backed Securities

examples/use-cases/ibor/Upserting a Large Payload.ipynb
=> CTECH-3358 reset portfolio for "Upserting a Large Payload"

requirements.txt
=> pin Drive SDK version

examples/use-cases/models-and-indices/Rebalancing with a model portfolio.ipynb
- Correct some grammar in a comment and note within the notebook
=> CD-10: Corrected some grammar in the comments and notes.

requirements.txt
=> SA-248 Added lumipy

examples/use-cases/instruments/FX Forward.ipynb
Update fx forwards to use individual txn type scope
=> Update FX Forwards to use custom transaction type scope

docker-compose.yml
=> Update dockerfile with venv

examples/use-cases/compliance/data/iag_allocations.csv, examples/use-cases/orders-management/data/amazon_allocations.csv, examples/use-cases/orders-management/data/live_orders.csv
=> DEV-14806: capitalise side

examples/use-cases/compliance/data/iag_allocations.csv, examples/use-cases/orders-management/data/amazon_allocations.csv, examples/use-cases/orders-management/data/live_orders.csv
=> Dev 14806 update side

analytics/FX/fx-forward-pricing-models.ipynb
=> ANA-4119: FX forward pricing methodology notebook

Index.ipynb, examples/use-cases/abor/Using Custodian Accounts.ipynb
=> Ibor 871: explicitly request custodian account property keys
